#!/bin/sh
# This file has been automatically generated by cygbuild
#
# Please do not remove section comments '#:<name>'

set -e

PATH=/bin:/sbin:/usr/bin:/usr/sbin
LC_ALL=C

dest=$1


#:etc
fromdir=/etc/defaults
for i in  etc/ etc/joe/ etc/joe/ftyperc etc/joe/jicerc.ru etc/joe/jmacsrc etc/joe/joerc etc/joe/joerc.zh_TW etc/joe/jpicorc etc/joe/jstarrc etc/joe/rjoerc etc/joe/shell.csh etc/joe/shell.sh
do
    from="$fromdir/$i"
    to="$dest/$i"

    [ -e "$from" ] || continue
    
    # Force install, the configuration files change from version to version
    # [ -e "$to"   ] && continue

    case "$i" in
        */) # Directory
            install -d -m 755 "$to"
            ;;
        *)  # File
            install -v -m 644 "$from" "$to"
            ;;
    esac
done

