#!/bin/sh
# Copyright (C) 2007-2009 Jari Aalto; Licenced under GPL v2 or later
#
# /etc/postinstall/<package>.sh -- Custom installation steps
#
# the :etc section is automatically generated by buils script

PATH="/bin:/usr/bin:/sbin:/usr/sbin:/usr/X11R6/bin:$PATH"

package="joe"

Environment()
{
    #  Define variables for the rest of the script

    [ "$1" ] && dest="$1"        # install destination

    if [ "$dest" ]; then
        #  Delete trailing slash
        dest=$(echo $dest | sed -e 's,/$,,' )
    fi

    #   This file will be installed as
    #   /etc/postinstall/<package>.sh so derive <package>
    #   But if this file is run from CYGIN-PATCHES/postinstall.sh
    #   then we do not know the package name

    name=$(echo $0 | sed -e 's,.*/,,' -e 's,\.sh,,' )

    if [ "$name" != "postinstall" ]; then
        package="$name"
    fi

    bindir="$dest/usr/bin"
    libdir="$dest/usr/lib"
    libdirx11="$dest/usr/lib/X11"
    includedir="$dest/usr/include"

    sharedir="$dest/usr/share"
    infodir="$sharedir/info"
    docdir="$sharedir/doc"
    etcdir="$dest/etc"

    #   1) list of files to be copied to /etc
    #   2) Source locations

    defaultsdir=$dest/etc/defaults/etc/$package
    manifestdir=$etcdir/postinstall
    conffile="$manifestdir/$package-manifest.lst"
}

Warn ()
{
    echo "$*" >&2
}

Run ()
{
    echo "$@"
    [ "$test" ] || "$@"
}

InstallConffiles ()
{
    [ ! -f "$conffile" ] && return

    #  Install default configuration files for system wide

    latest=$(LC_ALL=C find /usr/share/doc/$package*/ \
               -maxdepth 0 -type d \
             | sort | tail -1 | sed 's,/$,,')

    if [ ! "$latest" ]; then
        Warn "$0: [FATAL] Cannot find $package install doc dir"
        exit 1
    fi

    tmpprefix="${TEMPDIR:-/tmp}/tmp$$"
    clean="$tmpprefix.to"

    #  Filter out all comments. Grep only lines with filenames

    grep -E '^[^#]*/|^[[:space]]*$' $conffile > $clean

    while read from to
    do
        #  Both of these are are normally full file paths.
        #  - Translate few special "variables"
        #  - if TO is plain directory (ending to slash), reuse
        #    filename from FROM part.

        from=$(echo $dest$from | sed "s,\$PKGDOCDIR,$pkgdocdir$latest," )
        to=$(echo $dest$to | sed "s,\$PKG,$pkgdocdir," )

        [ ! "$from" ] && continue                       # empty line

        if [ ! "$to" ] ; then
            Warn "$conffile: [ERROR] in line: $from"
            continue
        fi

        if [ -d "$to" ] || echo $to | grep "/$" > /dev/null; then
            to=$(echo $to | sed 's,/$,,')
            to=$to/$(basename $from)
        fi

        #  Install only if a) not already there b) not changed

        name=$(basename $to)
        default=$defaultsdir/$name

        if [ ! -f "$to" ]; then
            Run install -m 0644 $from $to

        elif [ -f "$to" ] && [ ! -f "$default" ] ; then
                Warn "$0: [WARN] $to exists, no default"

        elif [ -f "$to" ] && [ -f "$from" ] ; then

            if cmp --quiet $default $to            # Same. No user changes
            then
                if ! cmp --quiet $from $default    # Not same. conf changes
                then
                    Run install -D -m 0644 $from $to
                fi
            else
                Warn "$0: [WARN] $to has changed." \
                     "Not installing new $from"
            fi
        fi

        #  Install new default from this package so that next install
        #  can compare if the file has stayed the same.

        Run install -D -m 0644 $from $default

    done < "$clean"

    rm -f "$clean"
}

Main()
{
    Environment "$@"    &&
    InstallConffiles
}

Main "$@"

# End of file
#:etc
fromdir=/etc/defaults
for i in   etc etc/postinstall etc/postinstall/joe-manifest.lst etc/joe etc/joe/joerc etc/joe/jicerc.ru etc/joe/jmacsrc etc/joe/jstarrc etc/joe/rjoerc etc/joe/jpicorc etc/joe/ftyperc etc/joe/lang etc/joe/lang/ru.po etc/joe/lang/de.po etc/joe/lang/fr.po etc/joe/syntax etc/joe/syntax/c.jsf etc/joe/syntax/perl.jsf etc/joe/syntax/verilog.jsf etc/joe/syntax/conf.jsf etc/joe/syntax/python.jsf etc/joe/syntax/php.jsf etc/joe/syntax/sh.jsf etc/joe/syntax/mail.jsf etc/joe/syntax/pascal.jsf etc/joe/syntax/html.jsf etc/joe/syntax/vhdl.jsf etc/joe/syntax/fortran.jsf etc/joe/syntax/java.jsf etc/joe/syntax/xml.jsf etc/joe/syntax/tcl.jsf etc/joe/syntax/lisp.jsf etc/joe/syntax/csh.jsf etc/joe/syntax/mason.jsf etc/joe/syntax/diff.jsf etc/joe/syntax/asm.jsf etc/joe/syntax/tex.jsf etc/joe/syntax/css.jsf etc/joe/syntax/ocaml.jsf etc/joe/syntax/4gl.jsf etc/joe/syntax/sml.jsf etc/joe/syntax/sql.jsf etc/joe/syntax/awk.jsf etc/joe/syntax/cobol.jsf etc/joe/syntax/sed.jsf etc/joe/syntax/ps.jsf etc/joe/syntax/ada.jsf etc/joe/syntax/troff.jsf etc/joe/syntax/haskell.jsf etc/joe/syntax/rexx.jsf etc/joe/syntax/skill.jsf etc/joe/syntax/lua.jsf etc/joe/syntax/ruby.jsf etc/joe/syntax/m4.jsf etc/joe/syntax/joerc.jsf etc/joe/charmaps etc/joe/charmaps/klingon etc/joe/doc etc/joe/doc/LIST etc/joe/doc/README etc/joe/doc/HINTS etc/joe/doc/ChangeLog etc/joe/doc/HACKING etc/joe/doc/NEWS
do
    src=$fromdir/$i
    dest=/$i

    [ -e $dest ] && continue

    if [ -d $src ] ; then
	install -d -m 755 $dest
	continue
    fi

    install -m 644 $src $dest
done

